# Generated by Django 5.0.7 on 2024-08-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('adhar_number', models.CharField(max_length=12, unique=True)),
                ('caste', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=70)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('family_annual_income', models.FloatField()),
                ('father_name', models.CharField(max_length=100)),
                ('passport', models.FileField(upload_to='documents/')),
                ('income_certificate', models.FileField(upload_to='documents/')),
                ('caste_certificate', models.FileField(upload_to='documents/')),
                ('domicile_certificate', models.FileField(upload_to='documents/')),
                ('adhar_card', models.FileField(upload_to='documents/')),
                ('hostel_form', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
