# Generated by Django 5.0.7 on 2024-08-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('adhar_number', models.CharField(max_length=12)),
                ('caste', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('family_details', models.TextField()),
                ('family_annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('father_name', models.CharField(max_length=100)),
                ('passport', models.FileField(upload_to='documents/')),
                ('income_certificate', models.FileField(upload_to='documents/')),
                ('caste_certificate', models.FileField(upload_to='documents/')),
                ('domicile_certificate', models.FileField(upload_to='documents/')),
                ('adhar_card', models.FileField(upload_to='documents/')),
                ('hostel_form', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
