# Generated by Django 5.0.7 on 2024-08-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp', '0002_application_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='father_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='stud_name',
            field=models.CharField(max_length=255),
        ),
    ]
